apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: st6-api
  namespace: st6
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: st6-api
                port:
                  number: 80
          - path: /actuator/health
            pathType: Exact
            backend:
              service:
                name: st6-api
                port:
                  number: 80
